### ISSUE TITLE
pm2 launch

### ISSUE THREAD

**Issue by JJJJJJJJJ504** [tacheometry/steam-hour-farmer#11]
how do I run this via pm2 if the steam guard code is used to log in to my account
![image](https://github.com/user-attachments/assets/9f604ed7-c822-4391-a5c5-5b83307714e9)

**Comment by tacheometry** [comment]
Not really practical - look at this section of the documentation again:

> When the bot starts, it will request a Steam Guard code via email or the mobile application. When you start playing on another machine, the bot will be kicked from its session, requiring a re-login, with a new Steam Guard code.
> 
> This can be remedied by using the Steam Shared Secret, or disabling Steam Guard.

So yeah, either disable the Steam Guard or use SteamDesktopAuthenticator and configure the environment variable for it 👍
