### ISSUE TITLE
Account name

### ISSUE THREAD

**Issue by exkor** [tacheometry/steam-hour-farmer#12]
[exkor@arch ~]$ steam-hour-farmer
Documentation: https://github.com/tacheometry/steam-hour-farmer
Environment variable "ACCOUNT_NAME" should be provided, but it is undefined.

How do I fix this please help

**Comment by tacheometry** [comment]
What have you tried from the **How to use** section of the document?

**Comment by exkor** [comment]
using pm2 seemed to somehow make it work but i just added shared secret and thats it

**Comment by tacheometry** [comment]
Maybe you were running the command inside a different directory, so it didn't find any `.env` file. Reopen this if you have anymore issues 😉
