### ISSUE TITLE
start in background

### ISSUE THREAD

**Issue by peterlaup** [tacheometry/steam-hour-farmer#4]
hi, im wondering how i can start the bot in background. If I start it with "steam-hour-farmer" and disconnect the SSH Session to the server afterwards, the bot will stop since its not a service. 
Please provide some information how to leave it running in the background or alternative starting methods. 
thanks

**Comment by peterlaup** [comment]
solved. created a service out of it - working in background

**Comment by tacheometry** [comment]
I added some info to the docs, thank you for mentioning 👍 And glad it's working now
