### ISSUE TITLE
Background running question

### ISSUE THREAD

**Issue by RGB-Outl4w** [tacheometry/steam-hour-farmer#5]
Hello! I was wondering if this application can be hosted as a web service (or something else) on a website like [render.com](https://render.com/). If anyone here has the experience of doing that, I nicely ask you to share it for a better understanding. Thanks!

**Comment by tacheometry** [comment]
I'm not sure these services are designed for that, but if you manage to get it working, please share your experience 👍

If you keep your PC on, you can also just run the program locally.

But I'd say the better route is investing in a VPS and hosting it on there. There are many options to choose from, including mini Linux servers that are cheap. Personally, I recommend/use [Contabo](https://contabo.com/en/vps/), but I also run more demanding services that use more resources.

**Comment by tacheometry** [comment]
Re-open the issue if needing help 👍
