### ISSUE TITLE
Specifying a custom game name

### ISSUE THREAD

**Issue by smdkx** [tacheometry/steam-hour-farmer#6]
Hi! Is it possible to specify your own game name in the “GAMES” parameter ? For example “GAMES”=“MY SUPER GAME NON STEAM”, but still have the selected games running (e.g. 570, 730). Or is there another parameter for this ?

**Comment by tacheometry** [comment]
If you update using `npm i -g steam-hour-farmer@latest` it should work 👍

**Comment by smdkx** [comment]
I'm using the latest version of steam-hour-farmer. But how can I specify my own game names instead of the standard ones? Is the “GAMES” parameter used for this ?

**Comment by smdkx** [comment]
I'm using the latest version of steam-hour-farmer. But how can I specify my own game names instead of the standard ones? Is the “GAMES” parameter used for this ?

**Comment by tacheometry** [comment]
I just published a new release, you should update again

**Comment by smdkx** [comment]
Yeah, it's working now! Thank you for the prompt reply and adding the new release!
