### ISSUE TITLE
Recent time vs overall time

### ISSUE THREAD

**Issue by WastedFreeTime** [tacheometry/steam-hour-farmer#8]
I guess its more of an steam problem but i just wanted to ask.
My overall time does not match up with the recent time after using your script.

![grafik](https://github.com/user-attachments/assets/8f74ec99-a0a8-409d-a658-cb9a17b78d4b)

Sorry it's german the picture displays 27 minutes recent time and 1 minute overall time. (Which makes no sense)
Did you also encounter this issue? It happens to every game i used your script for.

Thanks for the good script and your work!

**Comment by WastedFreeTime** [comment]
Okay it's taking steam a while to sync to the overall playtime if you use the api.

**Comment by tacheometry** [comment]
Ah, I'm glad it's working for you now

**Comment by tacheometry** [comment]
I never checked the recent time - I've only used this tool to have a ridiculous amount of hours in certain games, and "Last 2 weeks" in my profile 🙂

**Comment by WastedFreeTime** [comment]
Btw the limit is capped to 32 games which you can 'play' at the same time :)
